
### Register user
POST http://localhost:8080/register
Content-Type: application/json

{
    "email": "ash@my.de",
    "password": "pass!"
}

### Login
POST http://localhost:8080/login
Content-Type: application/json

{
    "email": "text@my.de",
    "password": "superSafe!"
}