### 

@endpoint = http://{{host}}:{{port}}/api
@host = localhost
@port = 8080


### 

GET {{endpoint}}/projects HTTP/1.1


### 

GET {{endpoint}}/projects/virtual-aquarium HTTP/1.1


### 

GET {{endpoint}}/projects/temple-diorama/sections HTTP/1.1
